### ISSUE TITLE
Taking Picture of Sparkline into SVG

### ISSUE THREAD

**Issue by Antoine2a** [CampusIoT/chirpstack-monitoring#2]
In order to send an email with a very precise summary. We want to send Sparkline into mails. 
The problem is not possible with javascript. 
The alternative is : Generate Sparkline, generate image and generate doc in svg.
Which is the objective of this issue

**Comment by Lambpaul** [comment]
Taking picture of sparkline into **PNG** works.
It is on the branch sparkline_dev
